### PR TITLE
Refactoring. Fixed bug where is doesnt work when called outside directory

### PR DESCRIPTION
**Pull request by meme-lord**
Refactoring. Fixed bug where is doesnt work when called outside directory

I used f-strings instead of adding strings together
Moved printing banner and other output to main, error output goes to stderr.
Cleaned up the output, eg. if the nameservers are output to a file we dont need them all spammed into stdout.
Now the script is suitable to be reused as a module if someone wanted.
Improved function and variable names
Updated twitter name and added github url.

If there's anything you think I should change before merging this pull request then let me know, for example by using fstrings the script wont work for python <3.6 (but people should be running that or newer on their machines by now).

### CODE REVIEW

**Comment by Abss0x7tbh** [comment]
Hey @meme-lord , i got about looking into this today. i have python3.6.10 installed. Apparently it does not support the dns module import i.e `ModuleNotFoundError: No module named 'dns'`

What's your solution to this ?

Thanks!

**Comment by meme-lord** [comment]
Try ```python -m pip install dnspython``` (replacing python with python3 or python3.6 if relevant) although I would like to point out that the dns import wasn't changed in my pull request so the old code should return the same error if you don't have the dnspython module installed.

**Comment by Abss0x7tbh** [comment]
I have the dnspython module installed and it works fine for the older version of python.

I followed your suggestion and had to install the remaining imports in the similar way to get the script working. Wondering why `pip3 install -r requirements.txt` (even with upgrade) doesn't do the deed.

But here's another issue i am facing. A probable issue in fetching the path of the file. Are you facing a similar issue on your end ? 


```
root@abss:~/test/bass# python3.6 bass.py -d paypal.com -o test-paypal
| |__   __ _ ___ ___
| '_ \ / _` / __/ __|
| |_) | (_| \__ \__ \
|_.__/ \__,_|___/___/
------------------------------------------
Author: @abss0x7tbh
Github: https://github.com/Abss0x7tbh/bass
------------------------------------------
DNS Providers : {'dynect', 'ultradns', 'public'}
Provider resolvers/dynect.txt not available. Add an issue with the name of the provider so that we can look into it
Provider resolvers/ultradns.txt not available. Add an issue with the name of the provider so that we can look into it
Provider resolvers/public.txt not available. Add an issue with the name of the provider so that we can look into it
Final List of Resolver located at test-paypal
Total usable resolvers : 0
```

**Comment by meme-lord** [comment]
I usually use something like ```python3 -m pip install -r requirements.txt ``` rather than ```pip3 install -r requirements.txt``` because it ensures the modules are being installed for the version of python you're actually using. Things get complicated if you have lots of python versions installed and pip3 might be installing for 3.8 when you're using 3.6 for example.

Also I just tested there and got the same error. Will comment again when I've fixed it.

**Comment by meme-lord** [comment]
Works now. The reason I didnt see this earlier was that it worked when you were outside the directory but not when you were in it. If you were in it then ```os.path.dirname(__file__)``` would return an empty string so the fix was this:
```
    script_dir = os.path.dirname(__file__)
    if script_dir == '':
        script_dir = '.'
```

**Comment by Abss0x7tbh** [comment]
Works like a charm. Nice fix! Thanks for your contributions! Much appreciated.

**Comment by Abss0x7tbh** [comment]
Hey @meme-lord , i would like to add you to the list of contributors. How shall i refer to you ?

**Comment by meme-lord** [comment]
Meme-lord is fine :)

**Comment by sawzeeyy** [comment]
Great work @meme-lord!

**Pull request merged**
